# Generated by Django 3.2.6 on 2021-08-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Genre de Production',
                'verbose_name_plural': 'Genres de Production',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='artistlabel',
            options={'managed': True, 'verbose_name': 'Artiste Client/Labelisé', 'verbose_name_plural': 'Artistes Clients/Labelisés'},
        ),
        migrations.AlterField(
            model_name='artistlabel',
            name='labeled',
            field=models.BooleanField(verbose_name='A fait parti du label ?'),
        ),
        migrations.AlterField(
            model_name='artistlabel',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Nom d'artiste"),
        ),
        migrations.AlterField(
            model_name='artistlabel',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='artistlabel',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Texte de présentation'),
        ),
        migrations.AlterModelTable(
            name='artistlabel',
            table='',
        ),
        migrations.CreateModel(
            name='Prodbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Titre')),
                ('reference', models.CharField(max_length=30, verbose_name='Référence')),
                ('music', models.FileField(upload_to='', verbose_name='Musique')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.prodtype')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
