# Generated by Django 3.2.6 on 2021-08-09 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20210808_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='LD2JContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom de scène du contributeur')),
            ],
            options={
                'verbose_name': 'Contributeur',
                'verbose_name_plural': 'Contributeurs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LD2JMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Titre')),
                ('contributors', models.ManyToManyField(to='label.LD2JContributor', verbose_name='Contributeurs')),
            ],
            options={
                'verbose_name': 'Musique',
                'verbose_name_plural': 'Musiques',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LD2JAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Titre de l'album")),
                ('relesead', models.TimeField(verbose_name='Date de sortie')),
                ('picture', models.ImageField(upload_to='', verbose_name='Jaquette')),
                ('hyperfollowlink', models.URLField(verbose_name='Lien Hyperfollow')),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.ld2jcontributor', verbose_name='Contributeurs')),
                ('musics', models.ManyToManyField(to='label.LD2JMusic', verbose_name='Musiques')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
