# Generated by Django 3.2.6 on 2021-08-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_ld2jalbum_ld2jcontributor_ld2jmusic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ld2jalbum',
            old_name='relesead',
            new_name='released',
        ),
        migrations.RemoveField(
            model_name='ld2jalbum',
            name='contributors',
        ),
        migrations.AddField(
            model_name='ld2jalbum',
            name='contributors',
            field=models.ManyToManyField(to='label.LD2JContributor', verbose_name='Contributeurs'),
        ),
    ]
