# Generated by Django 3.2.6 on 2021-08-09 10:07

from django.db import migrations
import label.models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_ld2jalbum_ld2jcontributor_ld2jmusic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ld2jalbum',
            name='released',
            field=label.models.DateWithoutTZField(verbose_name='Date de sortie'),
        ),
    ]
