# Generated by Django 3.2.6 on 2021-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_ld2jalbum_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodtype',
            name='example',
            field=models.FileField(blank=True, upload_to='', verbose_name='Instrumentale exemple'),
        ),
    ]
