# Generated by Django 3.2.6 on 2021-08-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_auto_20210809_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ld2jalbum',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='label.LD2JContributor', verbose_name='Contributeurs'),
        ),
        migrations.AlterField(
            model_name='ld2jalbum',
            name='released',
            field=models.DateField(verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='ld2jmusic',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='label.LD2JContributor', verbose_name='Contributeurs'),
        ),
    ]
