# Generated by Django 3.2.6 on 2021-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_prodtype_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodtype',
            name='example',
            field=models.FileField(default=None, upload_to='', verbose_name='Instrumentale exemple'),
        ),
    ]
